version: "3.1"
   
services:  
  db:
    container_name: watch_post
    image: postgres
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=post
    volumes:
      - ./postgress/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  web:
    container_name: watch_dj
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8200:8000
    restart: always
